Document: lbd
Title: Debian lbd Manual
Author: <insert document author here>
Abstract: This manual describes what lbd is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lbd/lbd.sgml.gz

Format: postscript
Files: /usr/share/doc/lbd/lbd.ps.gz

Format: text
Files: /usr/share/doc/lbd/lbd.text.gz

Format: HTML
Index: /usr/share/doc/lbd/html/index.html
Files: /usr/share/doc/lbd/html/*.html
